version : '3.8'

services:  
  meetus_service:
    container_name: meetus_service
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - app

networks:
  app:
    external: true 