version : '3.8'

services:  
   postgre-db:
    container_name: 'postgre-db'
    image: postgres:13.2
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    # expose:
    #   - 5432
    ports:
      - 5432:5432
    volumes:
      - /Users/iqbalnurhaq/Develop/postgres_data/13.2:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
    external: true 